### ISSUE TITLE
seg fault at search.cxx:2992

### ISSUE THREAD

**Issue by nikTheCosmoGuy** [pelahi/VELOCIraptor-STF#12]
This issue seems rare, in fact I found it when using a script to run Velociraptor on many snapshots and only failing only on the 147th one. 

```
gdb ./bin/stf-gas 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/stf-gas...done.
(gdb) run -i /home/nikolas/Simulations/100Mpc_DMAF/lcdm_100Mpc_128cubed/plain/snapshot_147 -s 1 -C /home/nikolas/Desktop/dump/hydrocosmological_run.cfg -o /home/nikolas/Desktop/dump/N128_plain_147
Starting program: /home/nikolas/VELOCIraptor-STF/stf/bin/stf-gas -i /home/nikolas/Simulations/100Mpc_DMAF/lcdm_100Mpc_128cubed/plain/snapshot_147 -s 1 -C /home/nikolas/Desktop/dump/hydrocosmological_run.cfg -o /home/nikolas/Desktop/dump/N128_plain_147
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2fc3700 (LWP 15738)]
[New Thread 0x7fffe8219700 (LWP 15739)]
[New Thread 0x7fffe7a18700 (LWP 15740)]
[New Thread 0x7fffe7217700 (LWP 15741)]
[New Thread 0x7fffe6a16700 (LWP 15742)]
[New Thread 0x7fffe6215700 (LWP 15743)]
[New Thread 0x7fffe5a14700 (LWP 15744)]
[New Thread 0x7fffe5213700 (LWP 15745)]
VELOCIraptor/STF running with MPI. Number of mpi threads: 1
VELOCIraptor/STF running with OpenMP. Number of openmp threads: 8
Reading config file
CONFIG INFO SUMMARY -------------------------- 
Searching all particles regardless of type
Field objects found with initial 3d FOF then use adaptive dispersion to find 6d FOFs
Baryons treated separately for substructure search and also FOF field search
Allowed potential to kinetic ratio when unbinding particles 0.95
Units: L=1, M=1e+10, V=1, G=43.0211
Searching for 6dfof cores so as to disentangle mergers
With with phase-space tensor core assignment
Gadget file particle input 
MPI input communication requires allocation of temporary particle buffer of size 0.0931323 GB.
 -------------------------- 
Read header ... 
There are 4194304 particles in total that require 0.40625GB of memory 
There are 2097152 baryon particles in total that require 0.203125GB of memory 
0 will also require additional memory for FOF algorithms and substructure search. Largest mem needed for preliminary FOF search. Rough estimate is 0.125GB of memory
Loading ... 
Each MPI read thread, of which there are 1, will allocate 0.09313221276 of memory to store particle data
Sending information to non-read threads in chunks of 961538 particles 
This requires approximately 4 receives
reading /home/nikolas/Simulations/100Mpc_DMAF/lcdm_100Mpc_128cubed/plain/snapshot_147
Cosmology (h,Omega_m,Omega_cdm,Omega_b,Omega_L) = (0.6774,0.3089,0.2603,0.0486,0.6911)
File contains 4194304 particles at is at time 0.4217276251
Particle system contains 4194304 particles at is at time 0.4217276251 in a box of size 100000
Done Loading
TIME::0 took 1.217560857 to load 4194304 of 4194304
Begin FOF search  of entire particle data set ... 
First build tree ... 
Done
Search particles using 3DFOF in physical space
Parameters used are : ellphys=97.27626427 Lunits (and likely 0.2 in interparticle spacing
0: Finished local search, nexport/nimport = 0 0 in 0.196852991
0: Starting to linking across MPI domains
0: finished linking across MPI domains in 0.359126249
MPI thread 0 has found 8558
Total number of groups found is 8558
0: finished FOF search in total time of 58.00510169
0 Adjusting for period 62256.80913
0: Sorting particles for 6dfof/phase-space search 
Search 714990 particles using 6DFOF with adaptive velocity scale
Static parameters used are : ellphys=97.27626427 Lunits
 reordering 4799 groups 
MPI thread 0 has found 4799
Total number of groups found is 4799
0 finished 6d/phase-space fof search in 14.87757693
0 Now store hierarchy information 
0 Done storing halo substructre level data
TIME::0 took 72.97233262 to search 4194304 with 8
Get inclusive masses
Done inclusive masses for field objects
0 search baryons 4194304 2097152
 of only baryons in FOF structures as baryons have already been grouped in FOF search 
sort particles so that tree only uses particles in groups 239686
Baryon search 2097152
FOF6D uses ellphys and ellvel.
Parameters used are : ellphys=97.27626427 Lunits, ellvel=1108.676673 Vunits.
Building tree to search dm containing 239686
Searching ...
Done
0 starting unbind of dm+baryons
Getting Hierarchy 4799
Done
0 Unbinding 4799 groups  ... 
0 Done. Number of groups remaining 4795
MPI thread 0 has found 4795
Total number of groups found is 4795
TIME::0 took 11.43776481 to search baryons  with 8
Getting Hierarchy 4795

Thread 1 "stf-gas" received signal SIGSEGV, Segmentation fault.
0x00000000004c16f0 in GetHierarchy (opt=..., ngroups=4795, nsub=0x195ada0, parentgid=0x1964390, uparentgid=0x196d980, stype=0x1976f70)
    at search.cxx:2992
2992	    for (int j=1;j<=papsldata[0]->nsinlevel;j++) {
(gdb) print j
$1 = 4799
(gdb) bt
#0  0x00000000004c16f0 in GetHierarchy (opt=..., ngroups=4795, nsub=0x195ada0, parentgid=0x1964390, uparentgid=0x196d980, stype=0x1976f70)
    at search.cxx:2992
#1  0x000000000043a400 in main (argc=9, argv=0x7fffffffddd8) at main.cxx:413
```

**Comment by nikTheCosmoGuy** [comment]
Fixed
