### ISSUE TITLE
Sometimes Segfaults

### ISSUE THREAD

**Issue by nikTheCosmoGuy** [pelahi/VELOCIraptor-STF#8]
Hi, Pascal, 

Thought I'd use this for reporting bugs instead of emails. I've got the most up to date version of VELOCIraptor.

Running on a plain gadget2 file some times fails.

```
./bin/stf-gas -i /home/nikolas/Simulations/100Mpc_DMAF/lcdm_100Mpc_128cubed/plain/snapshot_200 -s 1 -C /home/nikolas/Desktop/dump/hydrocosmological_run.cfg -o /home/nikolas/Desktop/dump/N128_plain
VELOCIraptor/STF running with OpenMP. Number of openmp threads: 8
Reading config file
CONFIG INFO SUMMARY -------------------------- 
Searching all particles regardless of type
Field objects found with initial 3d FOF then use adaptive dispersion to find 6d FOFs
Baryons treated separately for substructure search and also FOF field search
Allowed potential to kinetic ratio when unbinding particles 0.95
Units: L=1, M=1e+10, V=1, G=43.0211
Searching for 6dfof cores so as to disentangle mergers
With with phase-space tensor core assignment
Gadget file particle input 
 -------------------------- 
Read header ... 
There are 4194304 particles in total that require 0.40625GB of memory 
There are 2097152 baryon particles in total that require 0.203125GB of memory 
Loading ... 
reading /home/nikolas/Simulations/100Mpc_DMAF/lcdm_100Mpc_128cubed/plain/snapshot_200
Cosmology (h,Omega_m,Omega_cdm,Omega_b,Omega_L) = (0.6774,0.3089,0.2603,0.0486,0.6911)
File contains 4194304 particles at is at time 0.9999999828
Particle system contains 4194304 particles at is at time 0.9999999828 in a box of size 100000
Done Loading
TIME::0 took 0.957586743 to load 4194304
Begin FOF search  of entire particle data set ... 
First build tree ... 
Done
Search particles using 3DFOF in physical space
Parameters used are : ellphys=230.6613483 Lunits (and likely 0.2 in interparticle spacing
0: Get local velocity density
0 Using the following parameters to calculate velocity density using sph kernel: 0 (Nse,Nv)=256,32
0 Get velocity density using a subset of nearby physical or phase-space neighbours
Task 0 done 1.000023e-01 of its share 
Task 7 done 1.000023e-01 of its share 
Task 6 done 1.000023e-01 of its share 
Task 5 done 1.000023e-01 of its share 
Task 1 done 1.000023e-01 of its share 
0: finished local calculation in 5.564087556
0: finished FOF search in total time of 26.40376882
0 Adjusting for period 147623.2629
0: Sorting particles for 6dfof/phase-space search 
Segmentation fault (core dumped)
```

But it also seems to have worked fine when the input was the 64^3 particle version of the same snapshot. I was able to get out the halomass function for example.

Following up with gdb, and just checking a couple print statements

```
0: Sorting particles for 6dfof/phase-space search 

Thread 1 "stf-gas" received signal SIGSEGV, Segmentation fault.
0x000000000045de58 in SearchFullSet (opt=..., nbodies=nbodies@entry=4194304, Part=@0x7fffffffd048: 0x7fffd8ca4018, numgroups=@0x7fffffffd060: 8883) at search.cxx:252
252	    for (i=0;i<=numgroups;i++) numingroup[i]=noffset[i]=0;
(gdb) bt
#0  0x000000000045de58 in SearchFullSet (opt=..., nbodies=nbodies@entry=4194304, Part=@0x7fffffffd048: 0x7fffd8ca4018, numgroups=@0x7fffffffd060: 8883) at search.cxx:252
#1  0x0000000000405136 in main (argc=<optimised out>, argv=<optimised out>) at main.cxx:279
(gdb) print i
$1 = 0
(gdb) print numgroups
$2 = (Int_t &) @0x7fffffffd060: 8883
(gdb) print noffset[0]
$3 = 0
(gdb) print noffset[i]
$4 = 0
(gdb) print numingroup[0]
Cannot access memory at address 0x56fade0
(gdb) print numingroup
$5 = (Int_t *) 0x56fade0



```
I've commented out Debug='On' on and removed the -O2 flag

**Comment by pelahi** [comment]
Fixed.
